[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
  from = "/search"
  to = "https://mikenoel.pythonanywhere.com/api/v1/"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_BASE_URL"